03/14/2026 | 
Author: Cristian Ortega Singer | 
Mail: cris.ortega@fau.de

Load dependencies

In [1]:
from pathlib import Path
import subprocess
import pandas as pd
import json
import shutil
from datetime import datetime

Setup variables and presets

In [ ]:
SOURCE_ROOT = Path("downloads")
OUTPUT_ROOT = Path("normalized_mp4")

LOG_DIR = Path("logs")
LOG_DIR.mkdir(exist_ok=True, parents=True)

# Allowed input formats
VIDEO_EXTENSIONS = {".mkv", ".webm", ".mp4"}

# Dry run = print commands only, do not process files
DRY_RUN = True
# Limit processing for testing; set to None for full corpus
LIMIT = None #5 None
# Overwrite existing outputs?
OVERWRITE = False

# ffmpeg settings
VIDEO_CODEC = "libx264"
AUDIO_CODEC = "aac"
AUDIO_BITRATE = "192k"
CRF = 18
PRESET = "medium"

# Loudness normalization target
# EBU R128 style targets
LOUDNORM_I = -16
LOUDNORM_LRA = 11
LOUDNORM_TP = -1.5

# Resolution settings
MAX_LONG_EDGE = 854
DOWNSCALE_ONLY = True
#Frame rate normalization
TARGET_FPS = 25

# Logging
TIMESTAMP = datetime.now().strftime("%Y%m%d_%H%M%S")
PROCESS_LOG = LOG_DIR / f"conversion_log_{TIMESTAMP}.txt"
INVENTORY_CSV = LOG_DIR / f"corpus_inventory_{TIMESTAMP}.csv"
RESULTS_CSV = LOG_DIR / f"conversion_results_{TIMESTAMP}.csv"

Check for ffmpeg on path

In [3]:
def check_ffmpeg():
    ffmpeg_path = shutil.which("ffmpeg")
    ffprobe_path = shutil.which("ffprobe")
    
    print("ffmpeg:", ffmpeg_path)
    print("ffprobe:", ffprobe_path)
    
    if ffmpeg_path is None:
        raise RuntimeError("ffmpeg not found in PATH.")
    if ffprobe_path is None:
        raise RuntimeError("ffprobe not found in PATH.")
        
check_ffmpeg()

ffmpeg: C:\Users\CrisO\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-8.0.1-full_build\bin\ffmpeg.EXE
ffprobe: C:\Users\CrisO\AppData\Local\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\ffmpeg-8.0.1-full_build\bin\ffprobe.EXE

Establish helper functions

In [ ]:
def find_video_files(source_root: Path, allowed_exts=None):

    if allowed_exts is None:
        allowed_exts = VIDEO_EXTENSIONS
    
    files = []
    for path in source_root.rglob("*"):
        if path.is_file() and path.suffix.lower() in allowed_exts:
            files.append(path)
    return sorted(files)
 
def make_output_path(input_file: Path, source_root: Path, output_root: Path) -> Path:

    stem = input_file.stem
    output_file = output_root / f"{stem}.mp4"
    
    output_root.mkdir(parents=True, exist_ok=True)
    
    return output_file

def probe_streams(input_file: Path):

    # Use ffprobe to get stream information
    cmd = [
        "ffprobe",
        "-v", "error",
        "-print_format", "json",
        "-show_streams",
        "-show_format",
        str(input_file)
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        return None
    
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        return None


def summarize_probe(probe_data):

    # summary from ffprobe output
    if probe_data is None:
        return {
            "duration": None,
            "size": None,
            "bit_rate": None,
            "video_codec": None,
            "audio_codec": None,
            "width": None,
            "height": None,
            "audio_channels": None,
            "sample_rate": None,
        }
    
    format_info = probe_data.get("format", {})
    streams = probe_data.get("streams", [])
    
    video_stream = next((s for s in streams if s.get("codec_type") == "video"), {})
    audio_stream = next((s for s in streams if s.get("codec_type") == "audio"), {})
    
    return {
        "duration": format_info.get("duration"),
        "size": format_info.get("size"),
        "bit_rate": format_info.get("bit_rate"),
        "video_codec": video_stream.get("codec_name"),
        "audio_codec": audio_stream.get("codec_name"),
        "width": video_stream.get("width"),
        "height": video_stream.get("height"),
        "audio_channels": audio_stream.get("channels"),
        "sample_rate": audio_stream.get("sample_rate"),
    }


def build_scale_filter(max_long_edge=1280, downscale_only=True):
    
    # preserves aspect ratio of videos    
    if downscale_only:
        return (
            f"scale="
            f"'if(gte(iw,ih),min({max_long_edge},iw),-2)':"
            f"'if(gte(iw,ih),-2,min({max_long_edge},ih))':"
            f"flags=lanczos"
        )
    else:
        return (
            f"scale="
            f"'if(gte(iw,ih),{max_long_edge},-2)':"
            f"'if(gte(iw,ih),-2,{max_long_edge})':"
            f"flags=lanczos"
        )

Create csv with technical infos from ffprobe for each video

In [5]:
video_files = find_video_files(SOURCE_ROOT)
print(f"Found {len(video_files)} video files.")

inventory_rows = []

for vf in video_files:
    probe = probe_streams(vf)
    summary = summarize_probe(probe)
    
    row = {
        "input_path": str(vf),
        "parent_folder": str(vf.parent),
        "stem": vf.stem,
        "suffix": vf.suffix.lower(),
        **summary
    }
    inventory_rows.append(row)

inventory_df = pd.DataFrame(inventory_rows)
inventory_df.to_csv(INVENTORY_CSV, index=False)

print(f"Saved inventory to: {INVENTORY_CSV}")
inventory_df.head()

Found 2352 video files.
Saved inventory to: logs\corpus_inventory_20260313_234545.csv

,input_path,parent_folder,stem,suffix,duration,size,bit_rate,video_codec,audio_codec,width,height,audio_channels,sample_rate
0,downloads\2012-11-15_wtsSeRrOBZQ\2012-11-15_wt...,downloads\2012-11-15_wtsSeRrOBZQ,2012-11-15_wtsSeRrOBZQ,.mp4,104.582676,22780922,1742615,h264,aac,1280.0,720.0,2.0,44100
1,downloads\2013-04-26_8HHUta7n0y4\2013-04-26_8H...,downloads\2013-04-26_8HHUta7n0y4,2013-04-26_8HHUta7n0y4,.mkv,334.601000,61740238,1476151,h264,opus,1920.0,1080.0,2.0,48000
2,downloads\2013-04-26_bzkLtFLpWEg\2013-04-26_bz...,downloads\2013-04-26_bzkLtFLpWEg,2013-04-26_bzkLtFLpWEg,.mp4,242.718186,9225356,304068,h264,aac,854.0,480.0,2.0,44100
3,downloads\2013-04-26_eDrIDaJRwJ0\2013-04-26_eD...,downloads\2013-04-26_eDrIDaJRwJ0,2013-04-26_eDrIDaJRwJ0,.mp4,338.895238,31983030,754995,h264,aac,854.0,480.0,2.0,44100
4,downloads\2013-04-26_OKz_pgqQycc\2013-04-26_OK...,downloads\2013-04-26_OKz_pgqQycc,2013-04-26_OKz_pgqQycc,.mp4,438.299864,32051313,585011,h264,aac,854.0,480.0,2.0,44100

Inspect results

In [6]:
print("File count by extension:")
display(inventory_df["suffix"].value_counts())

print("\nVideo codec distribution:")
display(inventory_df["video_codec"].value_counts(dropna=False).head(20))

print("\nAudio codec distribution:")
display(inventory_df["audio_codec"].value_counts(dropna=False).head(20))

print("\nSample rate distribution:")
display(inventory_df["sample_rate"].value_counts(dropna=False).head(20))

File count by extension:

suffix
.mkv     1643
.webm     613
.mp4       96
Name: count, dtype: int64

Video codec distribution:

video_codec
h264    1739
vp9      484
av1      126
NaN        3
Name: count, dtype: int64

Audio codec distribution:

audio_codec
opus    2253
aac       96
NaN        3
Name: count, dtype: int64

Sample rate distribution:

sample_rate
48000    2255
44100      94
NaN         3
Name: count, dtype: int64

In [ ]:
inventory_df["width"] = pd.to_numeric(inventory_df["width"], errors="coerce")
inventory_df["height"] = pd.to_numeric(inventory_df["height"], errors="coerce")
inventory_df["long_edge"] = inventory_df[["width", "height"]].max(axis=1)

print("Resolution summary:")
display(inventory_df["long_edge"].describe())

print("\nVideos above x long edge:")
display((inventory_df["long_edge"] > 1280).value_counts())

print("\nMost common resolutions:")
display(
    inventory_df.groupby(["width", "height"])
    .size()
    .sort_values(ascending=False)
    .head(20)
)

Resolution summary:

count    2349.000000
mean     1931.633887
std       365.698243
min       480.000000
25%      1920.000000
50%      1920.000000
75%      1920.000000
max      3840.000000
Name: long_edge, dtype: float64

Videos above 1280 long edge:

long_edge
True     2243
False     109
Name: count, dtype: int64

Most common resolutions:

width   height
1920.0  1080.0    1871
1080.0  1920.0     307
3840.0  2160.0      54
1280.0  720.0       41
854.0   480.0       32
720.0   1280.0      18
640.0   480.0        8
3840.0  1634.0       6
640.0   360.0        4
360.0   640.0        2
270.0   480.0        1
1440.0  1080.0       1
1920.0  1020.0       1
        818.0        1
3840.0  1540.0       1
        1920.0       1
dtype: int64

ffmpeg builder

In [ ]:
def build_ffmpeg_command(input_file: Path, output_file: Path, overwrite=False):
 
    # conversion to mp4
    # resolution normalization
    # frame rate normalization
    # audio loudness normalization

    output_file.parent.mkdir(parents=True, exist_ok=True)
    overwrite_flag = "-y" if overwrite else "-n"

    loudnorm_filter = (
        f"loudnorm=I={LOUDNORM_I}:LRA={LOUDNORM_LRA}:TP={LOUDNORM_TP}"
    )

    scale_filter = build_scale_filter(
        max_long_edge=MAX_LONG_EDGE,
        downscale_only=DOWNSCALE_ONLY
    )

    video_filter = f"{scale_filter},fps={TARGET_FPS}"

    cmd = [
        "ffmpeg",
        overwrite_flag,
        "-i", str(input_file),

        "-map", "0:v:0?",
        "-map", "0:a:0?",

        "-vf", video_filter,

        "-c:v", VIDEO_CODEC,
        "-preset", PRESET,
        "-crf", str(CRF),

        "-c:a", AUDIO_CODEC,
        "-b:a", AUDIO_BITRATE,
        "-af", loudnorm_filter,

        "-movflags", "+faststart",

        str(output_file)
    ]

    return cmd

Preview of ffmpeg command call

In [19]:
sample_files = video_files[:LIMIT] if LIMIT is not None else video_files[:5]

for vf in sample_files:
    out = make_output_path(vf, SOURCE_ROOT, OUTPUT_ROOT)
    cmd = build_ffmpeg_command(vf, out, overwrite=OVERWRITE)
    print("INPUT :", vf)
    print("OUTPUT:", out)
    print("CMD   :", " ".join(cmd))
    print("-" * 80)

INPUT : downloads\2012-11-15_wtsSeRrOBZQ\2012-11-15_wtsSeRrOBZQ.mp4
OUTPUT: normalized_mp4\2012-11-15_wtsSeRrOBZQ.mp4
CMD   : ffmpeg -n -i downloads\2012-11-15_wtsSeRrOBZQ\2012-11-15_wtsSeRrOBZQ.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2012-11-15_wtsSeRrOBZQ.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-04-26_8HHUta7n0y4\2013-04-26_8HHUta7n0y4.mkv
OUTPUT: normalized_mp4\2013-04-26_8HHUta7n0y4.mp4
CMD   : ffmpeg -n -i downloads\2013-04-26_8HHUta7n0y4\2013-04-26_8HHUta7n0y4.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-04-26_8HHUta7n0y4.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-04-26_bzkLtFLpWEg\2013-04-26_bzkLtFLpWEg.mp4
OUTPUT: normalized_mp4\2013-04-26_bzkLtFLpWEg.mp4
CMD   : ffmpeg -n -i downloads\2013-04-26_bzkLtFLpWEg\2013-04-26_bzkLtFLpWEg.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-04-26_bzkLtFLpWEg.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-04-26_eDrIDaJRwJ0\2013-04-26_eDrIDaJRwJ0.mp4
OUTPUT: normalized_mp4\2013-04-26_eDrIDaJRwJ0.mp4
CMD   : ffmpeg -n -i downloads\2013-04-26_eDrIDaJRwJ0\2013-04-26_eDrIDaJRwJ0.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-04-26_eDrIDaJRwJ0.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-04-26_OKz_pgqQycc\2013-04-26_OKz_pgqQycc.mp4
OUTPUT: normalized_mp4\2013-04-26_OKz_pgqQycc.mp4
CMD   : ffmpeg -n -i downloads\2013-04-26_OKz_pgqQycc\2013-04-26_OKz_pgqQycc.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-04-26_OKz_pgqQycc.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-04-26_r7exgls85kg\2013-04-26_r7exgls85kg.mkv
OUTPUT: normalized_mp4\2013-04-26_r7exgls85kg.mp4
CMD   : ffmpeg -n -i downloads\2013-04-26_r7exgls85kg\2013-04-26_r7exgls85kg.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-04-26_r7exgls85kg.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-03_-Bf375yCUP8\2013-07-03_-Bf375yCUP8.mp4
OUTPUT: normalized_mp4\2013-07-03_-Bf375yCUP8.mp4
CMD   : ffmpeg -n -i downloads\2013-07-03_-Bf375yCUP8\2013-07-03_-Bf375yCUP8.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-03_-Bf375yCUP8.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-03_-P2nVYjqaNc\2013-07-03_-P2nVYjqaNc.mkv
OUTPUT: normalized_mp4\2013-07-03_-P2nVYjqaNc.mp4
CMD   : ffmpeg -n -i downloads\2013-07-03_-P2nVYjqaNc\2013-07-03_-P2nVYjqaNc.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-03_-P2nVYjqaNc.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-03_1K2NYb9Qg1o\2013-07-03_1K2NYb9Qg1o.mkv
OUTPUT: normalized_mp4\2013-07-03_1K2NYb9Qg1o.mp4
CMD   : ffmpeg -n -i downloads\2013-07-03_1K2NYb9Qg1o\2013-07-03_1K2NYb9Qg1o.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-03_1K2NYb9Qg1o.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-03_MUbvifkMXK8\2013-07-03_MUbvifkMXK8.mkv
OUTPUT: normalized_mp4\2013-07-03_MUbvifkMXK8.mp4
CMD   : ffmpeg -n -i downloads\2013-07-03_MUbvifkMXK8\2013-07-03_MUbvifkMXK8.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-03_MUbvifkMXK8.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-03_Nt7DeLYSzkk\2013-07-03_Nt7DeLYSzkk.mkv
OUTPUT: normalized_mp4\2013-07-03_Nt7DeLYSzkk.mp4
CMD   : ffmpeg -n -i downloads\2013-07-03_Nt7DeLYSzkk\2013-07-03_Nt7DeLYSzkk.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-03_Nt7DeLYSzkk.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-03_Ub-vVIXU4kE\2013-07-03_Ub-vVIXU4kE.mkv
OUTPUT: normalized_mp4\2013-07-03_Ub-vVIXU4kE.mp4
CMD   : ffmpeg -n -i downloads\2013-07-03_Ub-vVIXU4kE\2013-07-03_Ub-vVIXU4kE.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-03_Ub-vVIXU4kE.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-22_3249HNziLYQ\2013-07-22_3249HNziLYQ.mkv
OUTPUT: normalized_mp4\2013-07-22_3249HNziLYQ.mp4
CMD   : ffmpeg -n -i downloads\2013-07-22_3249HNziLYQ\2013-07-22_3249HNziLYQ.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-22_3249HNziLYQ.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-22_fKMYi5MKaHw\2013-07-22_fKMYi5MKaHw.mkv
OUTPUT: normalized_mp4\2013-07-22_fKMYi5MKaHw.mp4
CMD   : ffmpeg -n -i downloads\2013-07-22_fKMYi5MKaHw\2013-07-22_fKMYi5MKaHw.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-22_fKMYi5MKaHw.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-22_i8aoKtzoeYk\2013-07-22_i8aoKtzoeYk.mkv
OUTPUT: normalized_mp4\2013-07-22_i8aoKtzoeYk.mp4
CMD   : ffmpeg -n -i downloads\2013-07-22_i8aoKtzoeYk\2013-07-22_i8aoKtzoeYk.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-22_i8aoKtzoeYk.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-22_IqBcwdvrpkY\2013-07-22_IqBcwdvrpkY.mkv
OUTPUT: normalized_mp4\2013-07-22_IqBcwdvrpkY.mp4
CMD   : ffmpeg -n -i downloads\2013-07-22_IqBcwdvrpkY\2013-07-22_IqBcwdvrpkY.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-22_IqBcwdvrpkY.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-07-22_mN71ltMREcw\2013-07-22_mN71ltMREcw.mkv
OUTPUT: normalized_mp4\2013-07-22_mN71ltMREcw.mp4
CMD   : ffmpeg -n -i downloads\2013-07-22_mN71ltMREcw\2013-07-22_mN71ltMREcw.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-07-22_mN71ltMREcw.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-08-25__wQ51d8TFeI\2013-08-25__wQ51d8TFeI.mp4
OUTPUT: normalized_mp4\2013-08-25__wQ51d8TFeI.mp4
CMD   : ffmpeg -n -i downloads\2013-08-25__wQ51d8TFeI\2013-08-25__wQ51d8TFeI.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-08-25__wQ51d8TFeI.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-12_bXohZYOu28o\2013-09-12_bXohZYOu28o.mkv
OUTPUT: normalized_mp4\2013-09-12_bXohZYOu28o.mp4
CMD   : ffmpeg -n -i downloads\2013-09-12_bXohZYOu28o\2013-09-12_bXohZYOu28o.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-12_bXohZYOu28o.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-12_dwJdLf1Qr0w\2013-09-12_dwJdLf1Qr0w.mkv
OUTPUT: normalized_mp4\2013-09-12_dwJdLf1Qr0w.mp4
CMD   : ffmpeg -n -i downloads\2013-09-12_dwJdLf1Qr0w\2013-09-12_dwJdLf1Qr0w.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-12_dwJdLf1Qr0w.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-12_HOxg9DV6LNM\2013-09-12_HOxg9DV6LNM.mp4
OUTPUT: normalized_mp4\2013-09-12_HOxg9DV6LNM.mp4
CMD   : ffmpeg -n -i downloads\2013-09-12_HOxg9DV6LNM\2013-09-12_HOxg9DV6LNM.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-12_HOxg9DV6LNM.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-12_KLeW8ThmENQ\2013-09-12_KLeW8ThmENQ.mkv
OUTPUT: normalized_mp4\2013-09-12_KLeW8ThmENQ.mp4
CMD   : ffmpeg -n -i downloads\2013-09-12_KLeW8ThmENQ\2013-09-12_KLeW8ThmENQ.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-12_KLeW8ThmENQ.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-12_U88sczWL-vE\2013-09-12_U88sczWL-vE.mkv
OUTPUT: normalized_mp4\2013-09-12_U88sczWL-vE.mp4
CMD   : ffmpeg -n -i downloads\2013-09-12_U88sczWL-vE\2013-09-12_U88sczWL-vE.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-12_U88sczWL-vE.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-12_zMea1prFVQI\2013-09-12_zMea1prFVQI.mkv
OUTPUT: normalized_mp4\2013-09-12_zMea1prFVQI.mp4
CMD   : ffmpeg -n -i downloads\2013-09-12_zMea1prFVQI\2013-09-12_zMea1prFVQI.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-12_zMea1prFVQI.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-16_AhtKI1B7UY8\2013-09-16_AhtKI1B7UY8.mkv
OUTPUT: normalized_mp4\2013-09-16_AhtKI1B7UY8.mp4
CMD   : ffmpeg -n -i downloads\2013-09-16_AhtKI1B7UY8\2013-09-16_AhtKI1B7UY8.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-16_AhtKI1B7UY8.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-16_BlIaTtuX6-w\2013-09-16_BlIaTtuX6-w.mkv
OUTPUT: normalized_mp4\2013-09-16_BlIaTtuX6-w.mp4
CMD   : ffmpeg -n -i downloads\2013-09-16_BlIaTtuX6-w\2013-09-16_BlIaTtuX6-w.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-16_BlIaTtuX6-w.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-16_D0YdpJUkENo\2013-09-16_D0YdpJUkENo.mkv
OUTPUT: normalized_mp4\2013-09-16_D0YdpJUkENo.mp4
CMD   : ffmpeg -n -i downloads\2013-09-16_D0YdpJUkENo\2013-09-16_D0YdpJUkENo.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-16_D0YdpJUkENo.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-16_OtFON6w0Swo\2013-09-16_OtFON6w0Swo.mkv
OUTPUT: normalized_mp4\2013-09-16_OtFON6w0Swo.mp4
CMD   : ffmpeg -n -i downloads\2013-09-16_OtFON6w0Swo\2013-09-16_OtFON6w0Swo.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-16_OtFON6w0Swo.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_2-ROWGV9nO0\2013-09-18_2-ROWGV9nO0.mp4
OUTPUT: normalized_mp4\2013-09-18_2-ROWGV9nO0.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_2-ROWGV9nO0\2013-09-18_2-ROWGV9nO0.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_2-ROWGV9nO0.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_6B3KQC6yqjU\2013-09-18_6B3KQC6yqjU.mp4
OUTPUT: normalized_mp4\2013-09-18_6B3KQC6yqjU.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_6B3KQC6yqjU\2013-09-18_6B3KQC6yqjU.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_6B3KQC6yqjU.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_aFdLjr_MHJw\2013-09-18_aFdLjr_MHJw.mp4
OUTPUT: normalized_mp4\2013-09-18_aFdLjr_MHJw.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_aFdLjr_MHJw\2013-09-18_aFdLjr_MHJw.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_aFdLjr_MHJw.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_boFveLIX_WU\2013-09-18_boFveLIX_WU.mkv
OUTPUT: normalized_mp4\2013-09-18_boFveLIX_WU.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_boFveLIX_WU\2013-09-18_boFveLIX_WU.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_boFveLIX_WU.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_JFKuO-_Bgas\2013-09-18_JFKuO-_Bgas.mkv
OUTPUT: normalized_mp4\2013-09-18_JFKuO-_Bgas.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_JFKuO-_Bgas\2013-09-18_JFKuO-_Bgas.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_JFKuO-_Bgas.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_KNPLN2MtBJU\2013-09-18_KNPLN2MtBJU.mkv
OUTPUT: normalized_mp4\2013-09-18_KNPLN2MtBJU.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_KNPLN2MtBJU\2013-09-18_KNPLN2MtBJU.mkv -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_KNPLN2MtBJU.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_m4TGon4GEjs\2013-09-18_m4TGon4GEjs.mp4
OUTPUT: normalized_mp4\2013-09-18_m4TGon4GEjs.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_m4TGon4GEjs\2013-09-18_m4TGon4GEjs.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_m4TGon4GEjs.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_Nh8F-DzwbKg\2013-09-18_Nh8F-DzwbKg.mp4
OUTPUT: normalized_mp4\2013-09-18_Nh8F-DzwbKg.mp4
CMD   : ffmpeg -n -i downloads\2013-09-18_Nh8F-DzwbKg\2013-09-18_Nh8F-DzwbKg.mp4 -map 0:v:0? -map 0:a:0? -vf scale='if(gte(iw,ih),min(854,iw),-2)':'if(gte(iw,ih),-2,min(854,ih))':flags=lanczos,fps=25 -c:v libx264 -preset medium -crf 18 -c:a aac -b:a 192k -af loudnorm=I=-16:LRA=11:TP=-1.5 -movflags +faststart normalized_mp4\2013-09-18_Nh8F-DzwbKg.mp4
--------------------------------------------------------------------------------
INPUT : downloads\2013-09-18_qIuHBRexing\2013-09-18_qIuHBRexing.mkv
OUTPUT: normalized_mp4\2013-09-18_qIuHBRexing.mp4

Set up Process function

In [8]:
def run_command(cmd):
    return subprocess.run(cmd, capture_output=True, text=True)


def process_videos(
    files,
    source_root: Path,
    output_root: Path,
    dry_run=True,
    overwrite=False,
    log_file: Path | None = None
):
    results = []
    
    if log_file is not None:
        with open(log_file, "w", encoding="utf-8") as log:
            log.write(f"Processing started: {datetime.now().isoformat()}\n")
            log.write(f"Source root: {source_root}\n")
            log.write(f"Output root: {output_root}\n")
            log.write(f"Dry run: {dry_run}\n")
            log.write(f"Overwrite: {overwrite}\n\n")
    
    for i, input_file in enumerate(files, start=1):
        output_file = make_output_path(input_file, source_root, output_root)
        
        exists_already = output_file.exists()
        status = None
        returncode = None
        stderr_tail = None
        
        if exists_already and not overwrite:
            status = "skipped_exists"
        else:
            cmd = build_ffmpeg_command(input_file, output_file, overwrite=overwrite)
            
            if dry_run:
                status = "dry_run"
                returncode = 0
            else:
                result = run_command(cmd)
                returncode = result.returncode
                stderr_tail = result.stderr[-2000:] if result.stderr else None
                status = "ok" if result.returncode == 0 else "error"
        
        row = {
            "index": i,
            "input_file": str(input_file),
            "output_file": str(output_file),
            "status": status,
            "returncode": returncode,
            "output_exists": output_file.exists(),
            "stderr_tail": stderr_tail
        }
        results.append(row)
        
        print(f"[{i}/{len(files)}] {status}: {input_file.name}")
        
        if log_file is not None:
            with open(log_file, "a", encoding="utf-8") as log:
                log.write(json.dumps(row, ensure_ascii=False) + "\n")
    
    return pd.DataFrame(results)

Run pipeline

In [ ]:
input_files = video_files[:LIMIT] if LIMIT is not None else video_files
results_df = process_videos(
    files=input_files,
    source_root=SOURCE_ROOT,
    output_root=OUTPUT_ROOT,
    dry_run=False,
    overwrite=OVERWRITE,
    log_file=PROCESS_LOG
)

results_df.to_csv(RESULTS_CSV, index=False)

print(f"Saved processing results to: {RESULTS_CSV}")
print(f"Saved log to: {PROCESS_LOG}")

results_df.head()

[1/2352] skipped_exists: 2012-11-15_wtsSeRrOBZQ.mp4
[2/2352] skipped_exists: 2013-04-26_8HHUta7n0y4.mkv
[3/2352] skipped_exists: 2013-04-26_bzkLtFLpWEg.mp4
[4/2352] skipped_exists: 2013-04-26_eDrIDaJRwJ0.mp4
[5/2352] skipped_exists: 2013-04-26_OKz_pgqQycc.mp4
[6/2352] skipped_exists: 2013-04-26_r7exgls85kg.mkv
[7/2352] skipped_exists: 2013-07-03_-Bf375yCUP8.mp4
[8/2352] skipped_exists: 2013-07-03_-P2nVYjqaNc.mkv
[9/2352] skipped_exists: 2013-07-03_1K2NYb9Qg1o.mkv
[10/2352] skipped_exists: 2013-07-03_MUbvifkMXK8.mkv
[11/2352] skipped_exists: 2013-07-03_Nt7DeLYSzkk.mkv
[12/2352] skipped_exists: 2013-07-03_Ub-vVIXU4kE.mkv
[13/2352] skipped_exists: 2013-07-22_3249HNziLYQ.mkv
[14/2352] skipped_exists: 2013-07-22_fKMYi5MKaHw.mkv
[15/2352] skipped_exists: 2013-07-22_i8aoKtzoeYk.mkv
[16/2352] skipped_exists: 2013-07-22_IqBcwdvrpkY.mkv
[17/2352] skipped_exists: 2013-07-22_mN71ltMREcw.mkv
[18/2352] skipped_exists: 2013-08-25__wQ51d8TFeI.mp4
[19/2352] skipped_exists: 2013-09-12_bXohZYOu28o.mkv
[20/2352] skipped_exists: 2013-09-12_dwJdLf1Qr0w.mkv
[21/2352] skipped_exists: 2013-09-12_HOxg9DV6LNM.mp4
[22/2352] skipped_exists: 2013-09-12_KLeW8ThmENQ.mkv
[23/2352] skipped_exists: 2013-09-12_U88sczWL-vE.mkv
[24/2352] skipped_exists: 2013-09-12_zMea1prFVQI.mkv
[25/2352] skipped_exists: 2013-09-16_AhtKI1B7UY8.mkv
[26/2352] skipped_exists: 2013-09-16_BlIaTtuX6-w.mkv
[27/2352] skipped_exists: 2013-09-16_D0YdpJUkENo.mkv
[28/2352] skipped_exists: 2013-09-16_OtFON6w0Swo.mkv
[29/2352] skipped_exists: 2013-09-18_2-ROWGV9nO0.mp4
[30/2352] skipped_exists: 2013-09-18_6B3KQC6yqjU.mp4
[31/2352] skipped_exists: 2013-09-18_aFdLjr_MHJw.mp4
[32/2352] skipped_exists: 2013-09-18_boFveLIX_WU.mkv
[33/2352] skipped_exists: 2013-09-18_JFKuO-_Bgas.mkv
[34/2352] skipped_exists: 2013-09-18_KNPLN2MtBJU.mkv
[35/2352] skipped_exists: 2013-09-18_m4TGon4GEjs.mp4
[36/2352] skipped_exists: 2013-09-18_Nh8F-DzwbKg.mp4
[37/2352] skipped_exists: 2013-09-18_qIuHBRexing.mkv
[38/2352] skipped_exists: 2013-09-18_R130xHrdphQ.mkv
[39/2352] skipped_exists: 2013-09-18_sQnnVLHWlgw.mkv
[40/2352] skipped_exists: 2013-09-18_T6WXAIDYX5o.mkv
[41/2352] skipped_exists: 2013-09-18_wlVF6nP4BkM.mp4
[42/2352] skipped_exists: 2013-09-18_XeN0KnnkmhU.mp4
[43/2352] skipped_exists: 2013-09-18_YeUYW8nSJto.mkv
[44/2352] skipped_exists: 2013-09-18_zwFK6nj7vHM.mkv
[45/2352] skipped_exists: 2013-09-24_AcnEqBZ8F10.mp4
[46/2352] skipped_exists: 2013-09-24_JNULg3gX9Vw.mkv
[47/2352] skipped_exists: 2013-09-24_uJKgnt8iGoY.mp4
[48/2352] skipped_exists: 2013-09-24_vZywTSOecYY.mkv
[49/2352] skipped_exists: 2013-09-25_07fidtvKsyg.mkv
[50/2352] skipped_exists: 2013-09-25__-qFdCSWHaY.mkv
[51/2352] skipped_exists: 2013-09-25_AKZ9NK9tsOM.mkv
[52/2352] skipped_exists: 2013-09-25_BPkEL7RAASw.mkv
[53/2352] skipped_exists: 2013-09-25_cxHtDrR2TF0.mkv
[54/2352] skipped_exists: 2013-09-25_EAgOnCMNzIM.mkv
[55/2352] skipped_exists: 2013-09-25_exuv9PAgbdk.mkv
[56/2352] skipped_exists: 2013-09-25_f27ZUgktEFQ.mp4
[57/2352] skipped_exists: 2013-09-25_Gje_xakw-Ks.mp4
[58/2352] skipped_exists: 2013-09-25_J0yTogSwm5s.mkv
[59/2352] skipped_exists: 2013-09-25_jdpXUAXr7nQ.mkv
[60/2352] skipped_exists: 2013-09-25_K5OG4nUpF_w.mkv
[61/2352] skipped_exists: 2013-09-25_L0JPdd1F6nE.mkv
[62/2352] skipped_exists: 2013-09-25_ptHTKbqW4_k.mkv
[63/2352] skipped_exists: 2013-09-25_uHqrhTl8Zno.mp4
[64/2352] skipped_exists: 2013-09-25_xBJRjePuLK4.mkv
[65/2352] skipped_exists: 2013-09-25_yAYDA1Cf4_Q.mkv
[66/2352] skipped_exists: 2013-09-25_zh6ioNW_LJM.mkv
[67/2352] skipped_exists: 2013-09-27_6QWXk8lMBx4.mkv
[68/2352] skipped_exists: 2013-09-27_9iKBS6DOXV4.mp4
[69/2352] skipped_exists: 2013-09-27_AWwuDTp9iGM.mp4
[70/2352] skipped_exists: 2013-09-27_lrNEUxpL-b0.mp4
[71/2352] skipped_exists: 2013-09-27_oyyrMchlXrY.mp4
[72/2352] skipped_exists: 2013-09-27_vcD1RX0WNig.mp4
[73/2352] skipped_exists: 2013-10-01_6sLykGavOgw.mkv
[74/2352] skipped_exists: 2013-10-01_80nWyOFYzOY.mp4
[75/2352] skipped_exists: 2013-10-01_ehK-koGgmUI.mkv
[76/2352] skipped_exists: 2013-10-01_lG2xWulLog8.mkv
[77/2352] skipped_exists: 2013-10-01_m8aa8Sb8Y14.mp4
[78/2352] skipped_exists: 2013-10-10_0kTaOaadpsA.mkv
[79/2352] skipped_exists: 2013-10-10_8SNDN345DHQ.mkv
[80/2352] skipped_exists: 2013-10-10__U22BgF0KzM.mp4
[81/2352] skipped_exists: 2013-10-10_as7yv5q1yGI.mp4
[82/2352] skipped_exists: 2013-10-10_GNJq7eQ6tGo.mkv
[83/2352] skipped_exists: 2013-10-10_JBUxcSGb3Es.mkv
[84/2352] skipped_exists: 2013-10-10_MqbACETeXvc.mkv
[85/2352] skipped_exists: 2013-10-10_ofLYSwapjGg.mkv
[86/2352] skipped_exists: 2013-10-10_zHPi_agi7tE.mp4
[87/2352] skipped_exists: 2013-11-02_6Q92zPn3aw4.mkv
[88/2352] skipped_exists: 2013-11-02_BcW9TeDfBY0.mkv
[89/2352] skipped_exists: 2013-11-02_DhiXCJiQTto.mkv
[90/2352] skipped_exists: 2013-11-02_eNuaZPHmmxg.mkv
[91/2352] skipped_exists: 2013-11-02_guazwTHt95o.mkv
[92/2352] skipped_exists: 2013-11-02_kX68anx5vqA.webm
[93/2352] skipped_exists: 2013-11-02_p60UlpnFqDc.mkv
[94/2352] skipped_exists: 2013-12-05_-DMdEsnOAao.mkv
[95/2352] skipped_exists: 2013-12-05_HCp4BYYTRjY.mkv
[96/2352] skipped_exists: 2013-12-05_hO7L7RI4YO0.mkv
[97/2352] skipped_exists: 2013-12-05_nYTofUNlPto.mkv
[98/2352] skipped_exists: 2013-12-05_O4uiMTOVAyE.mkv
[99/2352] skipped_exists: 2013-12-05_RCRG75L2gQc.mp4
[100/2352] skipped_exists: 2013-12-05_Rn3S43-vHnU.mkv
[101/2352] skipped_exists: 2013-12-05_rnLA6wvklXQ.mkv
[102/2352] skipped_exists: 2013-12-05_z3eNBwL93-o.mkv
[103/2352] skipped_exists: 2013-12-31_05b3OBKa4D8.mkv
[104/2352] skipped_exists: 2013-12-31_cVwA0V_c2Kw.mkv
[105/2352] skipped_exists: 2013-12-31_idzmL6nEpRA.mkv
[106/2352] skipped_exists: 2013-12-31_ITKAAWCDd00.mkv
[107/2352] skipped_exists: 2013-12-31_l8T1ATWHzjY.mkv
[108/2352] skipped_exists: 2013-12-31_lAsmV3nE-FA.mkv
[109/2352] skipped_exists: 2013-12-31_Ph_onMZSNrw.mkv
[110/2352] skipped_exists: 2013-12-31_r92S1c4RnXs.mkv
[111/2352] skipped_exists: 2013-12-31_T4ZTnDW5XaU.mkv
[112/2352] skipped_exists: 2013-12-31_U8Mf-Q99GU0.mkv
[113/2352] skipped_exists: 2014-01-05_3nVU_JWxg0A.mkv
[114/2352] skipped_exists: 2014-01-05_C8LQyaeEUdQ.mkv
[115/2352] skipped_exists: 2014-01-05_D5pKma36-ps.mp4
[116/2352] skipped_exists: 2014-01-05_oHKuZuc_dGE.mkv
[117/2352] skipped_exists: 2014-01-06_-2mcqnW4-pk.mkv
[118/2352] skipped_exists: 2014-01-06_0O1UZlUCAKc.mkv
[119/2352] skipped_exists: 2014-01-06_AebytRQZA-8.mkv
[120/2352] skipped_exists: 2014-01-06_eWa6RnviJpY.mkv
[121/2352] skipped_exists: 2014-01-06_S_sOpRDNoiY.mkv
[122/2352] skipped_exists: 2014-01-06_vXMCgZCXoeA.mkv
[123/2352] skipped_exists: 2014-01-06_YpfVHnR_-nQ.mkv
[124/2352] skipped_exists: 2014-02-02_3hvtkJ0cP4I.mkv
[125/2352] skipped_exists: 2014-02-02_77Z0N2YUhEA.mkv
[126/2352] skipped_exists: 2014-02-02_BcdOkobZ0_Y.mkv
[127/2352] skipped_exists: 2014-02-02_cKyvTyBXYvo.mkv
[128/2352] skipped_exists: 2014-02-02_G6w6XEIH2zE.mp4
[129/2352] skipped_exists: 2014-02-02_Iwbc0PbTWCE.mkv
[130/2352] skipped_exists: 2014-02-02_MJeDwhcnl7Q.mkv
[131/2352] skipped_exists: 2014-02-02_sUBcSr_G24I.mkv
[132/2352] skipped_exists: 2014-02-02_Xh6zX5xvXEU.mkv
[133/2352] skipped_exists: 2014-02-02_yGhsd2moldg.mp4
[134/2352] skipped_exists: 2014-02-02_zkUIDMJHPwk.mkv
[135/2352] skipped_exists: 2014-02-16_FW9Mv624xcg.mp4
[136/2352] skipped_exists: 2014-02-16_j7K7awdAulk.mkv
[137/2352] skipped_exists: 2014-02-16_jg0DH66dlqU.mkv
[138/2352] skipped_exists: 2014-02-16_RbnBdqCqbFU.mkv
[139/2352] skipped_exists: 2014-02-16_rfpXsuO3wNI.mp4
[140/2352] skipped_exists: 2014-02-16_zadEKBt4Vy0.mp4
[141/2352] skipped_exists: 2014-03-02_68RaZI4bzDw.mp4
[142/2352] skipped_exists: 2014-03-02_9nK40haWDn4.mp4
[143/2352] skipped_exists: 2014-03-02_aqKmYT9uENc.mkv
[144/2352] skipped_exists: 2014-03-02_dd2TUUM8VME.mp4
[145/2352] skipped_exists: 2014-03-02_fhbHCDoCwE8.mp4
[146/2352] skipped_exists: 2014-03-02_lCO7ejB0vGA.mkv
[147/2352] skipped_exists: 2014-03-02_PNtmnwzr0tM.mkv
[148/2352] skipped_exists: 2014-03-02_RHe8kYwwllI.mkv
[149/2352] skipped_exists: 2014-03-02_zdoofqDJTXY.mkv
[150/2352] skipped_exists: 2014-03-13_9OJgQZOs-fo.mkv
[151/2352] skipped_exists: 2014-03-13__5nIRdswRf8.mp4
[152/2352] skipped_exists: 2014-03-13_DP1svg8OTSw.mkv
[153/2352] skipped_exists: 2014-03-13_luIyoUuH_rE.mkv
[154/2352] skipped_exists: 2014-03-13_M--7MVejANg.mp4
[155/2352] skipped_exists: 2014-03-16_coxV719s1qU.mkv
[156/2352] skipped_exists: 2014-03-16_DeGKY6Qofmw.mp4
[157/2352] skipped_exists: 2014-03-16_f_OkKymjvX4.mp4
[158/2352] skipped_exists: 2014-03-16_lmJn0rwrUE8.mkv
[159/2352] skipped_exists: 2014-03-16_MdERHC9H7jU.mkv
[160/2352] skipped_exists: 2014-03-16_N0I3aFNH1S4.mkv
[161/2352] skipped_exists: 2014-03-16_nI65AXUnTQM.mkv
[162/2352] skipped_exists: 2014-03-16_NR1mVMLvaak.mkv
[163/2352] skipped_exists: 2014-03-16_S5Xl2laMgyg.mkv
[164/2352] skipped_exists: 2014-03-16_utch6Q6Z1DE.mkv
[165/2352] skipped_exists: 2014-03-21_-K87b5uHdkU.mkv
[166/2352] skipped_exists: 2014-03-21_7Zahxk2w1Bc.mp4
[167/2352] skipped_exists: 2014-03-21_CKXDFypVwlY.mp4
[168/2352] skipped_exists: 2014-03-21_I7a5eT8amd0.mkv
[169/2352] skipped_exists: 2014-03-21_jt9EZudXxqk.mkv
[170/2352] skipped_exists: 2014-03-21_TjCrCFYcGd8.mp4
[171/2352] skipped_exists: 2014-05-02_3qN9QZCkk7c.mkv
[172/2352] skipped_exists: 2014-05-02_7T231WzTKzQ.mkv
[173/2352] skipped_exists: 2014-05-02_9Zl3fNQmiCo.mkv
[174/2352] skipped_exists: 2014-05-02_IKEZIDzV9uU.mkv
[175/2352] skipped_exists: 2014-05-02_jLkfp783-Jc.mp4
[176/2352] skipped_exists: 2014-05-02_PvBPpWi4twQ.mkv
[177/2352] skipped_exists: 2014-05-02_QlRuBZ-W3gw.mkv
[178/2352] skipped_exists: 2014-05-02_twFd19_cAwE.mkv
[179/2352] skipped_exists: 2014-05-02_u8EIsSudgCY.mkv
[180/2352] skipped_exists: 2014-05-02_zAbR1Be1MGo.mp4
[181/2352] skipped_exists: 2014-06-15_0Qd2TVNuNH0.mkv
[182/2352] skipped_exists: 2014-06-15_DZUkjCw7gkc.mkv
[183/2352] skipped_exists: 2014-06-15_PMz_CS3cxqw.mkv
[184/2352] skipped_exists: 2014-06-15_ruyIc32KLYg.mkv
[185/2352] skipped_exists: 2014-06-15_XzA7_Koo2fQ.mkv
[186/2352] skipped_exists: 2014-06-15_Y6aYeLrTw8o.mkv
[187/2352] skipped_exists: 2014-08-12_wq64SmsCfr8.mp4
[188/2352] skipped_exists: 2014-11-04_1oaYVXJhXcg.mkv
[189/2352] skipped_exists: 2014-11-04_9h1yrph-VjM.mkv
[190/2352] skipped_exists: 2014-11-04_nTWOnUt_O08.mkv
[191/2352] skipped_exists: 2014-11-04_uAekXW2nGh0.mkv
[192/2352] skipped_exists: 2014-11-04_VVZcXEw5uo8.mkv
[193/2352] skipped_exists: 2014-11-04_ZgycTmHgakM.mkv
[194/2352] skipped_exists: 2014-11-21_3VmN2bDATSI.mkv
[195/2352] skipped_exists: 2014-11-21_9lR6gO-z2qY.mkv
[196/2352] skipped_exists: 2014-11-21_Eqxzkw_OJog.mkv
[197/2352] skipped_exists: 2014-11-21_vONymgclwl4.mkv
[198/2352] skipped_exists: 2014-11-21_ydUxS9jnnTg.mkv
[199/2352] skipped_exists: 2014-11-24_CvDM71S6wks.mkv
[200/2352] skipped_exists: 2014-11-30_4L6BvPhNrAc.mkv
[201/2352] skipped_exists: 2014-11-30_6qfihR3-Odg.mkv
[202/2352] skipped_exists: 2014-11-30_8yh80Lyqsdo.mkv
[203/2352] skipped_exists: 2014-11-30_putyS1rrStg.mkv
[204/2352] skipped_exists: 2014-12-27_w3oL1nQIMNw.mp4
[205/2352] skipped_exists: 2014-12-29_aXlZxhdyndw.mkv
[206/2352] skipped_exists: 2014-12-29_gxVz3335NcU.mkv
[207/2352] skipped_exists: 2014-12-29_JLZZ2iglb7k.mkv
[208/2352] skipped_exists: 2014-12-29_n3woAPE64iM.mkv
[209/2352] skipped_exists: 2014-12-29_RQSa5i3JZ5Y.mkv
[210/2352] skipped_exists: 2014-12-29_XE2yPUfyPj4.mkv
[211/2352] skipped_exists: 2015-01-18_8_FUAOi1XRA.mkv
[212/2352] skipped_exists: 2015-01-18_Deg90pmKfM8.mkv
[213/2352] skipped_exists: 2015-01-18_fXJNZOqOmSo.mkv
[214/2352] skipped_exists: 2015-01-18_M04nMpMK2gg.mkv
[215/2352] skipped_exists: 2015-01-18_RM2oWr4FWKQ.mkv
[216/2352] skipped_exists: 2015-01-22_D1aZsghytn0.mkv
[217/2352] skipped_exists: 2015-01-22_IZaAOT6tGFc.mkv
[218/2352] skipped_exists: 2015-01-22_Jivq4umEhGg.mkv
[219/2352] skipped_exists: 2015-01-22_UhQrI_2vcdM.mkv
[220/2352] skipped_exists: 2015-01-22_xdmshl7rOwI.mkv
[221/2352] skipped_exists: 2015-02-16_9CwHBThUS38.mkv
[222/2352] skipped_exists: 2015-02-16__cQjqm-W2mM.mkv
[223/2352] skipped_exists: 2015-02-16_E9TlMz6PrKw.mkv
[224/2352] skipped_exists: 2015-02-16_KGWpQWj08LI.mkv
[225/2352] skipped_exists: 2015-02-16_ogHkGtJED48.mkv
[226/2352] skipped_exists: 2015-02-16_Szr6c7NP7bg.mp4
[227/2352] skipped_exists: 2015-02-16_VGa4roB2tRE.mp4
[228/2352] skipped_exists: 2015-02-23_-F28uWHpm2c.mkv
[229/2352] skipped_exists: 2015-02-23_1EIGytf0rVU.mkv
[230/2352] skipped_exists: 2015-02-23_5-4SB7fG1MY.mp4
[231/2352] skipped_exists: 2015-02-23_kLLyjW96Ez0.mp4
[232/2352] skipped_exists: 2015-02-23_M60fUPFpsVA.mp4
[233/2352] skipped_exists: 2015-02-23_qxZp0vV0z_4.mkv
[234/2352] skipped_exists: 2015-02-23_t3KKsaxFETU.mkv
[235/2352] skipped_exists: 2015-02-25_7FOynk9IWUI.mkv
[236/2352] skipped_exists: 2015-02-25_fPJMtkf20bI.mkv
[237/2352] skipped_exists: 2015-02-25_FqmYQ5AHGfc.mp4
[238/2352] skipped_exists: 2015-02-25_KylKrPy2MTY.mkv
[239/2352] skipped_exists: 2015-02-26_xFDiN-07bms.mkv
[240/2352] skipped_exists: 2015-02-26_z11LKt_XT9w.mkv
[241/2352] skipped_exists: 2015-03-01_W5-KRTfAuIk.mkv
[242/2352] skipped_exists: 2015-03-04_48Rj_-GDtdQ.mkv
[243/2352] skipped_exists: 2015-03-04_8o6AWLnHN5M.mkv
[244/2352] skipped_exists: 2015-03-04_agJ3FwJXeD4.mkv
[245/2352] skipped_exists: 2015-03-04_ddZfZJah67Y.mkv
[246/2352] skipped_exists: 2015-03-04_HsB4afN8LWE.mkv
[247/2352] skipped_exists: 2015-03-04_sesOeirMzrk.mkv
[248/2352] skipped_exists: 2015-03-04_UKlryCNBKpU.mkv
[249/2352] skipped_exists: 2015-03-04_YHvWNKH51og.mkv
[250/2352] skipped_exists: 2015-03-10_Onj8ri0ZLzc.mkv
[251/2352] skipped_exists: 2015-03-10_TkGksCivkxw.mkv
[252/2352] skipped_exists: 2015-04-20_1C2TxFT2-pM.mkv
[253/2352] skipped_exists: 2015-04-20_2PDKUpGOa1U.mkv
[254/2352] skipped_exists: 2015-04-20_7KI2SmBK7ok.mkv
[255/2352] skipped_exists: 2015-04-20_b1xOldkAEjg.mkv
[256/2352] skipped_exists: 2015-04-20_K-g8oNzmMbE.mkv
[257/2352] skipped_exists: 2015-04-20_PulxfstP-8Q.mkv
[258/2352] skipped_exists: 2015-04-20_X5LjTjHBTiY.mkv
[259/2352] skipped_exists: 2015-04-21_KCG_BbGbwpg.mkv
[260/2352] skipped_exists: 2015-04-24_jHnueOvHfC4.mkv
[261/2352] skipped_exists: 2015-04-28_-AekFHL-LpQ.webm
[262/2352] skipped_exists: 2015-04-28_7u0I0UNseZs.mp4
[263/2352] skipped_exists: 2015-04-28_E9i8AOfOTN0.mkv
[264/2352] skipped_exists: 2015-04-28_MR8k7mfgHTc.mkv
[265/2352] skipped_exists: 2015-04-28_N6jDbbkWm8E.mkv
[266/2352] skipped_exists: 2015-04-28_zZMVrXo7pgk.mkv
[267/2352] skipped_exists: 2015-05-12_-O8jXX02UUM.mkv
[268/2352] skipped_exists: 2015-05-12_1nGDL73mEwQ.mkv
[269/2352] skipped_exists: 2015-05-12_EMXoR_oOUfM.mkv
[270/2352] skipped_exists: 2015-05-12_jw5w42aTtMA.mkv
[271/2352] skipped_exists: 2015-05-12_nZaB_AsJd8w.mkv
[272/2352] skipped_exists: 2015-05-12_pjOkyOw73KI.mkv
[273/2352] skipped_exists: 2015-05-12_TLMtw08FGZw.mkv
[274/2352] skipped_exists: 2015-05-12_un9foLjbJR4.mkv
[275/2352] skipped_exists: 2015-05-18_bBjMBuyFHWc.mkv
[276/2352] skipped_exists: 2015-05-18_ILGURMFW008.mkv
[277/2352] skipped_exists: 2015-05-18_jT7STJhGW7A.mkv
[278/2352] skipped_exists: 2015-05-18_KSJy5SDYma8.mkv
[279/2352] skipped_exists: 2015-05-18_MTfWgyIgbsU.mkv
[280/2352] skipped_exists: 2015-05-18_R1rxCMx04XM.mkv
[281/2352] skipped_exists: 2015-05-18_TQPH5sHb7iA.mkv
[282/2352] skipped_exists: 2015-06-01_DNLhAA31X3M.mkv
[283/2352] skipped_exists: 2015-06-01_fX3pLyda7Ew.mkv
[284/2352] skipped_exists: 2015-06-01_LNmNwBIsHlM.mkv
[285/2352] skipped_exists: 2015-06-01_NzjVe-pDanI.mkv
[286/2352] skipped_exists: 2015-06-01_qc_s5A4yNvM.mkv
[287/2352] skipped_exists: 2015-06-01_T-QW7BjGZAs.mkv
[288/2352] skipped_exists: 2015-06-01_x0kbQPZrFYI.mkv
[289/2352] skipped_exists: 2015-06-15_I3yW-W9sQq8.mkv
[290/2352] skipped_exists: 2015-06-16_rqd_3thtaHc.mkv
[291/2352] skipped_exists: 2015-06-17_-537glv-RGQ.mkv
[292/2352] skipped_exists: 2015-06-18_Hw-yDaSr0fU.mkv
[293/2352] skipped_exists: 2015-06-18_MV_3LLyuAqA.mkv
[294/2352] skipped_exists: 2015-06-19_CTd6SXlNGyw.mkv
[295/2352] skipped_exists: 2015-06-22_NzHdoXdXdCs.mkv
[296/2352] skipped_exists: 2015-06-22_PvOEnWkK1-k.mkv
[297/2352] skipped_exists: 2015-06-23_pXVVK1sw8iA.mkv
[298/2352] skipped_exists: 2015-06-24_JmE6ImXsf3k.mkv
[299/2352] skipped_exists: 2015-06-25_OEFJgERGXp0.mkv
[300/2352] skipped_exists: 2015-06-25_vV8yCZG9tvw.mkv
[301/2352] skipped_exists: 2015-06-26_6RqgXPj_qnk.mkv
[302/2352] skipped_exists: 2015-06-30_DlIn4pvT6WE.mkv
[303/2352] skipped_exists: 2015-07-01_v_Y077gR064.mkv
[304/2352] skipped_exists: 2015-07-02_4LDCoooCB2M.mkv
[305/2352] skipped_exists: 2015-07-05_Pj8hDRBg-AI.mkv
[306/2352] skipped_exists: 2015-07-06_5ZKdzfvKhoQ.webm
[307/2352] skipped_exists: 2015-07-07_eTpn6x19xUs.mkv
[308/2352] skipped_exists: 2015-07-10_VG6WE_jmEdc.mkv
[309/2352] skipped_exists: 2015-08-17_vtPs5x4oeeQ.mkv
[310/2352] skipped_exists: 2015-08-18_l8SWjGY3HaE.mkv
[311/2352] skipped_exists: 2015-08-19_EFLgs9p1ElQ.webm
[312/2352] skipped_exists: 2015-08-22_1s3b2kXFICA.mkv
[313/2352] skipped_exists: 2015-08-23_rKfHcSZYFnk.mkv
[314/2352] skipped_exists: 2015-08-25_ij2iLZUh8hw.mkv
[315/2352] skipped_exists: 2015-08-26_qXSVlAdj8ms.mkv
[316/2352] skipped_exists: 2015-08-27_37hjypbbpP8.webm
[317/2352] skipped_exists: 2015-08-28_g-Pq5YnQ-Wg.mkv
[318/2352] skipped_exists: 2015-08-29_xPUbNcaGOXc.mkv
[319/2352] skipped_exists: 2015-08-30_FxZs4qX4ZlE.mkv
[320/2352] skipped_exists: 2015-08-31_hhMgskwpExc.webm
[321/2352] skipped_exists: 2015-09-01_KJwsKCzMB1o.mkv
[322/2352] skipped_exists: 2015-09-02_Xi96pAG2FmM.mkv
[323/2352] skipped_exists: 2015-09-03_9yZknhPfs9w.mkv
[324/2352] skipped_exists: 2015-09-05_HCd_cZCJKTI.webm
[325/2352] skipped_exists: 2015-09-06_FMtvciI4eJA.webm
[326/2352] skipped_exists: 2015-09-07_4_xrnZZGYY4.mkv
[327/2352] skipped_exists: 2015-09-08_aHnegfi4gWU.mkv
[328/2352] skipped_exists: 2015-09-09_i7Z3hvSGUZs.mkv
[329/2352] skipped_exists: 2015-09-10_aCGMl4hd3eQ.mkv
[330/2352] skipped_exists: 2015-09-11_XxH71umdn_M.mkv
[331/2352] skipped_exists: 2015-09-11_zCyzyDIxV1E.mkv
[332/2352] skipped_exists: 2015-09-13_I_GnRsO9ROc.mkv
[333/2352] skipped_exists: 2015-09-14_wiRVgO8ULzk.mkv
[334/2352] skipped_exists: 2015-09-15_rQ9sueN68qo.mkv
[335/2352] skipped_exists: 2015-09-16_dgJQOnKPbj4.mkv
[336/2352] skipped_exists: 2015-09-17_jeHIiVNVYKk.mkv
[337/2352] skipped_exists: 2015-09-20_jeKvNt4A2BY.mkv
[338/2352] skipped_exists: 2015-09-21_iZc0YwOGIaM.mkv
[339/2352] skipped_exists: 2015-09-22_59bdJadPcRs.mkv
[340/2352] skipped_exists: 2015-09-23_BTEkC2KLU7U.mkv
[341/2352] skipped_exists: 2015-09-25_PMx2PT3aEVY.mkv
[342/2352] skipped_exists: 2015-09-26_A3GHukT3yvk.mkv
[343/2352] skipped_exists: 2015-09-28_FL7QzCBCQZU.mkv
[344/2352] skipped_exists: 2015-09-29_ArHcf46MArg.mkv
[345/2352] skipped_exists: 2015-09-30_bNfAFFOkKmM.mkv
[346/2352] skipped_exists: 2015-10-01_-gzXEzf6lSY.mkv
[347/2352] skipped_exists: 2015-10-02_uDWJVhT8OKk.mkv
[348/2352] skipped_exists: 2015-10-03_ocmBVICx7AU.mkv
[349/2352] skipped_exists: 2015-10-04_kfzVn1zxGfo.mkv
[350/2352] skipped_exists: 2015-10-05_y4yDmlsqyvM.mkv
[351/2352] skipped_exists: 2015-10-06_6Pcvsg8SCP8.mkv
[352/2352] skipped_exists: 2015-10-07_Wwdxb9v2tp8.mkv
[353/2352] skipped_exists: 2015-10-08_6kQJIkB9qos.mp4
[354/2352] skipped_exists: 2015-10-09_jKopnzVMju0.mkv
[355/2352] skipped_exists: 2015-10-10_9zIyAq_QD-w.mkv
[356/2352] skipped_exists: 2015-10-11_lf5lzWA7R1I.mkv
[357/2352] skipped_exists: 2015-10-12_KwYL_ZB6e_4.mkv
[358/2352] skipped_exists: 2015-10-13_qScdFf_yXYA.mkv
[359/2352] skipped_exists: 2015-10-15_uYdU53FLT1E.mkv
[360/2352] skipped_exists: 2015-10-17_Qr1mPcLwWI8.mkv
[361/2352] skipped_exists: 2015-10-18_-Ig_eb71vuI.mkv
[362/2352] skipped_exists: 2015-10-19_w-7a06WGHlw.mkv
[363/2352] skipped_exists: 2015-10-26_tdZ1O2C-C6U.mkv
[364/2352] skipped_exists: 2015-10-27_df_EaM5PVfw.mkv
[365/2352] skipped_exists: 2015-10-28_e3KPrfLX-B0.mkv
[366/2352] skipped_exists: 2015-10-30_k9I42ZMmox4.mkv
[367/2352] skipped_exists: 2015-10-31_Y5PEZGY4yCM.mkv
[368/2352] skipped_exists: 2015-11-01_ycG2su-zx2w.mkv
[369/2352] skipped_exists: 2015-11-02_pVDXAZ1DEbY.mkv
[370/2352] skipped_exists: 2015-11-03_oWmOplSyKoY.mkv
[371/2352] skipped_exists: 2015-11-06_UbpgNVNkhKM.mkv
[372/2352] skipped_exists: 2015-11-08_NMwwZU0Svrg.mkv

,index,input_file,output_file,status,returncode,output_exists,stderr_tail
0,1,downloads\2012-11-15_wtsSeRrOBZQ\2012-11-15_wt...,normalized_mp4\2012-11-15_wtsSeRrOBZQ.mp4,skipped_exists,NaN,True,NaN
1,2,downloads\2013-04-26_8HHUta7n0y4\2013-04-26_8H...,normalized_mp4\2013-04-26_8HHUta7n0y4.mp4,skipped_exists,NaN,True,NaN
2,3,downloads\2013-04-26_bzkLtFLpWEg\2013-04-26_bz...,normalized_mp4\2013-04-26_bzkLtFLpWEg.mp4,skipped_exists,NaN,True,NaN
3,4,downloads\2013-04-26_eDrIDaJRwJ0\2013-04-26_eD...,normalized_mp4\2013-04-26_eDrIDaJRwJ0.mp4,skipped_exists,NaN,True,NaN
4,5,downloads\2013-04-26_OKz_pgqQycc\2013-04-26_OK...,normalized_mp4\2013-04-26_OKz_pgqQycc.mp4,skipped_exists,NaN,True,NaN

Verify output

In [5]:
normalized_files = find_video_files(OUTPUT_ROOT, allowed_exts={".mp4"})
print(f"Normalized mp4 files found: {len(normalized_files)}")

normalized_rows = []
for vf in normalized_files:
    probe = probe_streams(vf)
    summary = summarize_probe(probe)
    normalized_rows.append({
        "output_path": str(vf),
        "suffix": vf.suffix.lower(),
        **summary
    })

normalized_df = pd.DataFrame(normalized_rows)
normalized_df.head()

Normalized mp4 files found: 1421

,output_path,suffix,duration,size,bit_rate,video_codec,audio_codec,width,height,audio_channels,sample_rate
0,normalized_mp4\2012-11-15_wtsSeRrOBZQ.mp4,.mp4,104.600000,22150991,1694148,h264,aac,854.0,480.0,2.0,96000
1,normalized_mp4\2013-04-26_8HHUta7n0y4.mp4,.mp4,334.607000,52548412,1256361,h264,aac,854.0,480.0,2.0,96000
2,normalized_mp4\2013-04-26_bzkLtFLpWEg.mp4,.mp4,242.800000,19154273,631112,h264,aac,854.0,480.0,2.0,96000
3,normalized_mp4\2013-04-26_eDrIDaJRwJ0.mp4,.mp4,338.900000,48354056,1141435,h264,aac,854.0,480.0,2.0,96000
4,normalized_mp4\2013-04-26_OKz_pgqQycc.mp4,.mp4,438.300000,49490014,903308,h264,aac,854.0,480.0,2.0,96000

In [6]:
print("Output suffix distribution:")
display(normalized_df["suffix"].value_counts(dropna=False))

print("\nOutput video codec distribution:")
display(normalized_df["video_codec"].value_counts(dropna=False))

print("\nOutput audio codec distribution:")
display(normalized_df["audio_codec"].value_counts(dropna=False))

print("\nOutput sample rates:")
display(normalized_df["sample_rate"].value_counts(dropna=False).head(10))

Output suffix distribution:

suffix
.mp4    1421
Name: count, dtype: int64

Output video codec distribution:

video_codec
h264    1420
NaN        1
Name: count, dtype: int64

Output audio codec distribution:

audio_codec
aac    1420
NaN       1
Name: count, dtype: int64

Output sample rates:

sample_rate
96000    1420
NaN         1
Name: count, dtype: int64

In [7]:
normalized_files = find_video_files(OUTPUT_ROOT, allowed_exts={".mp4"})

normalized_rows = []
for vf in normalized_files:
    probe = probe_streams(vf)
    summary = summarize_probe(probe)
    normalized_rows.append({
        "output_path": str(vf),
        **summary
    })

normalized_df = pd.DataFrame(normalized_rows)
normalized_df["width"] = pd.to_numeric(normalized_df["width"], errors="coerce")
normalized_df["height"] = pd.to_numeric(normalized_df["height"], errors="coerce")
normalized_df["long_edge"] = normalized_df[["width", "height"]].max(axis=1)

print("Converted resolution summary:")
display(normalized_df["long_edge"].describe())

print("\nAny outputs above target?")
display((normalized_df["long_edge"] > MAX_LONG_EDGE).value_counts())

print("\nMost common output resolutions:")
display(
    normalized_df.groupby(["width", "height"])
    .size()
    .sort_values(ascending=False)
    .head(20)
)

Converted resolution summary:

count    1420.000000
mean      852.191549
std        19.596132
min       640.000000
25%       854.000000
50%       854.000000
75%       854.000000
max       854.000000
Name: long_edge, dtype: float64

Any outputs above target?

long_edge
False    1421
Name: count, dtype: int64

Most common output resolutions:

width  height
854.0  480.0     1402
640.0  480.0        8
       360.0        4
854.0  364.0        3
       342.0        1
       454.0        1
       640.0        1
dtype: int64

In [8]:
normalized_df["fps"] = normalized_df["bit_rate"]  # placeholder column

def get_fps(path):
    cmd = [
        "ffprobe",
        "-v", "0",
        "-select_streams", "v:0",
        "-show_entries", "stream=r_frame_rate",
        "-of", "default=noprint_wrappers=1:nokey=1",
        str(path)
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout.strip()

fps_values = []

for vf in normalized_files:
    fps_values.append(get_fps(vf))

print("Frame rate distribution:")
pd.Series(fps_values).value_counts()

Frame rate distribution:

25/1    1420
           1
Name: count, dtype: int64